# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Writing your first project with Java 11, Maven and JUnit5

on:
  push:
    branches: [ master, solution-*]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up OpenJDK 11.0.2
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.2
    - name: Build with Maven
      run: mvn clean test --file pom.xml
